Keywords

Context:
Acme Studios, a major Hollywood production company, maintains a vast movie database that tracks detailed information about their films, 
including genres, keywords, and cast. Understanding audience preferences for specific movie categories is crucial for informing production decisions and marketing strategies.

You are a data analyst at Acme Studios. Your manager has asked you to compile a list of all movies that contain the keywords 'sport', 'sequel', or 'suspense'. 
This data will be used to tailor marketing strategies and recommend relevant content to viewers.

Problem Statement:
Write a query to list down all the movies along with their details that have keywords like 'sport' or 'sequel' or 'suspense'.

Result:
Return the columns 'original_title', 'director', 'genres', 'cast', 'budget', 'revenue', 'runtime', and 'vote_average'.
Return the columns ordered by original_title in ascending order.
  
Dataset description for 'movies' table:
id - tmdb movie id
imdb_id - imdb movie id
popularity - A numeric quantity specifying the movie popularity.
budget - The budget in which the movie was made.
revenue - The worldwide revenue generated by the movie.
original_title - The title of the movie
cast - The name of the lead and supporting actors.
homepage - A link to the homepage of the movie.
director - The name of the director of the movie
tagline - Movie tagline.
keywords - The keywords or tags related to the movie.
overview - A brief description of the movie.
runtime - The running time of the movie in minutes.
genres - The genres of the movies
production_companies - The production house of the movie.
release_date - the date on which it was released.
vote_count - the count of votes received.
vote_average - average ratings the movie received.
release_year - the year in which it was released.

QUERY:

SELECT original_title, director, genres, cast, budget, revenue, runtime, vote_average
FROM movies
WHERE keywords LIKE '%sport%' OR keywords LIKE '%sequel%' OR keywords LIKE '%suspense%'
ORDER BY original_title;
